spring:
  datasource:
    url: jdbc:mysql://52.78.205.215:3306/fitple_project
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    url: jdbc:mysql://localhost:3306/fitple_project
#    username: root
#    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
      org.hibernate: DEBUG

jwt:
  secret: b1ee7f2bb90b78b2274f86936a50c6619fdd96ab9ca837f7902b3f53cc8992ff4b45a58b91cfd1103f85281ea694151d7e83ea0e36d91e022d124223317caf07
server:
  port: 8080

cors:
  allowed-origins: https://www.gymsparttest.shop, http://localhost:7070
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

cloud:
  aws:
    s3:
      bucket: gymsparta-test
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

toss:
  payments:
    client-secret: test_ck_AQ92ymxN342KQZW5Ym64rajRKXvd
    secret-key: test_sk_GjLJoQ1aVZ9KQRgbxBkJ3w6KYe2R

kakao:
  pay:
    cid: TC0ONETIME  # 테스트용 CID
    client-id: A7EAB5C0E188BA0EF82B  # 클라이언트 ID
    client-secret: 749696A87ABCFA738A36  # 클라이언트 시크릿
    secret-key: PRD441A04CE52647D4E94FFA919FD67242007B40  # 시크릿 키