###로그인
POST http://localhost:8080/login
Content-Type: application/json

{
  "accountId": "testuser1",
  "password": "testpassword"
}

> {%
  client.test("로그인 성공", function() {
    var response = client.global.response;
    var accessToken = response.headers["authorization"].substring(7); // "Bearer " 제거
    client.global.set("Authorization", 'Bearer ' + accessToken);
  });
%}

###매장 등록
POST http://localhost:8080/api/stores/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjEiLCJpYXQiOjE3MjE4MjA4NzEsImV4cCI6MTcyMTgyMjY3MX0.jNBdV-bW5AcorTEuBXhFknIFUNYE053NJb4aftPoZmY

{
  "storeName": "매장명123467",
  "address": "주소",
  "streetAddress": "상세 주소",
  "postalCode": "우편 번호123",
  "storeInfo": "매장 설명",
  "storeHour": "운영 시간",
  "storeTel": "매장 전화번호"
}

###매장 정보 수정
PUT http://localhost:8080/api/stores/admin/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjEiLCJpYXQiOjE3MjE4MjA4NzEsImV4cCI6MTcyMTgyMjY3MX0.jNBdV-bW5AcorTEuBXhFknIFUNYE053NJb4aftPoZmY

{
  "storeName": "매장명 수정1",
  "address": "주소",
  "streetAddress": "상세 주소",
  "postalCode": "우편 번호",
  "storeInfo": "매장 설명",
  "storeHour": "운영 시간",
  "storeTel": "매장 전화번호"
}

###매장 삭제
DELETE http://localhost:8080/api/stores/admin/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjEiLCJpYXQiOjE3MjE4MjA4NzEsImV4cCI6MTcyMTgyMjY3MX0.jNBdV-bW5AcorTEuBXhFknIFUNYE053NJb4aftPoZmY

###매장 전체 조회
GET http://localhost:8080/api/stores
Content-Type: application/json

###매장 상세 조회
GET http://localhost:8080/api/stores/9
Content-Type: application/json

###점주 매장 조회
GET http://localhost:8080/api/stores/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjEiLCJpYXQiOjE3MjE4MjA4NzEsImV4cCI6MTcyMTgyMjY3MX0.jNBdV-bW5AcorTEuBXhFknIFUNYE053NJb4aftPoZmY

###점주 매장 상세 조회
GET http://localhost:8080/api/stores/admin/9
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjEiLCJpYXQiOjE3MjE4MjA4NzEsImV4cCI6MTcyMTgyMjY3MX0.jNBdV-bW5AcorTEuBXhFknIFUNYE053NJb4aftPoZmY