###회원가입
POST http://localhost:8080/user/signup
Content-Type: application/json

{
  "userName": "qwre",
  "accountId": "testuser1",
  "password": "testpassword",
  "confirmPassword": "testpassword",
  "email": "testuser1@example.com"
}

### 로그인
POST http://localhost:8080/login
Content-Type: application/json

{
  "accountId": "testuser",
  "password": "testpassword"
}

> {%
  client.test("로그인 성공", function() {
    var response = client.global.response;
    var jsonResponse = JSON.parse(response.body);
    var accessToken = response.headers["authorization"].substring(7); // "Bearer " 제거
    client.global.set("accessToken", accessToken);
  });
%}

### 응답에서 access_token을 추출하여 변수에 저장
@access_token = your_access_token_here

### 로그아웃
POST http://localhost:8080/logout
Authorization: Bearer {{access_token}}

### 회원탈퇴
DELETE http://localhost:8080/profile/users/signout
Authorization: Bearer {{access_token}}