### 트레이너 전체 조회
GET localhost:8080/api/trainers
Content-Type: application/json

### 트레이너 로그인
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "accountId": "qwe",
  "password": "심재훈"
}

### 트레이너 프로필 변경
PUT http://localhost:8080/api/profile/trainer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJxd2UiLCJpYXQiOjE3MjIwNzgxNjksImV4cCI6MTcyMjA3OTk2OX0.1Oq2NbDXZT83pRpHtE6u62vYDBM7kb4I3BbelQby0-s

{
  "nickname": "트레이너아에리",
  "trainerInfo": "저는 골드 2입ㄴ다",
  "trainerPicture": "골드2사진",
  "trainerPhoneNumber": "01091429069",
  "email": "sonael121@naver.com",
  "password": "ael121667"
}

### 트레이너 비번 변경
PUT http://localhost:8080/api/profile/trainer/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJxd2UiLCJpYXQiOjE3MjIwNzgxNjksImV4cCI6MTcyMjA3OTk2OX0.1Oq2NbDXZT83pRpHtE6u62vYDBM7kb4I3BbelQby0-s

{
  "oldPassword": "ael121667",
  "newPassword": "심재훈"
}

### 트레이너 프로필 조회
GET http://localhost:8080/api/profile/trainer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJxd2UiLCJpYXQiOjE3MjIwNzgxNjksImV4cCI6MTcyMjA3OTk2OX0.1Oq2NbDXZT83pRpHtE6u62vYDBM7kb4I3BbelQby0-s

{
}